name: 'CloudFormation Deploy'
description: 'Deploy to AWS CloudFormation using Python 3.11 and AWS CLI'
inputs:
  aws_access_key_id:
    description: 'The AWS access key id'
    required: true
    default: ""
  aws_secret_access_key:
    description: 'The AWS secret access key'
    required: true
    default: ""
  # optional
  aws_region:
    description: 'The AWS region. Fallback to "eu-west-1"'
    required: false
    default: "eu-west-1"
  cf_stack_prefix:
    description: 'The prefix for the CloudFormation stack name. Fallback to repo name.'
    required: false
    default: ""
  env_name:
    description: 'The environment (will be added as suffix to the stack prefix). Fallback to branch name.'
    required: false
    default: ""
  domain:
    description: 'The domain. '
    required: false
    default: ""
  domain_role_arn:
    description: 'The domain role ARN'
    required: false
    default: ""
  cert_role_arn:
    description: 'The certificate role ARN'
    required: false
    default: ""
  docker_compose_path:
    description: 'The docker compose path. Defaults to "docker-compose.yaml"'
    required: false
    default: ""
  aws_compose_path:
    description: 'The AWS compose path. Defaults to "aws-compose-x.yaml"'
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
    AWS_REGION: ${{ inputs.aws_region }}
  args:
    - --aws-region=${{ inputs.aws_region }}
    - --cf-stack-prefix=${{ inputs.cf_stack_prefix }}
    - --environment=${{ inputs.env_name }}
    - --docker-compose-path=${{ inputs.docker_compose_path }}
    - --aws-compose-path=${{ inputs.aws_compose_path }}
    - --elb-domain=${{ inputs.domain }}
    - --elb-domain-role-arn=${{ inputs.domain_role_arn }}
