name: 'CloudFormation Deploy'
description: 'Deploy to AWS CloudFormation using Python 3.11 and AWS CLI'
inputs:
  cf-stack-prefix:
    description: 'The prefix for the CloudFormation stack name. Fallback to repo name.'
    required: false
    default: ""
  env-name:
    description: 'The environment (will be added as suffix to the stack prefix). Fallback to branch name.'
    required: false
    default: ""
  docker-compose-path:
    description: 'The docker compose path. Defaults to "docker-compose.yaml"'
    required: false
    default: ""
  ecs-compose-x-sub:
    description: 'A JSON string containing the ECS compose substitutes. Defaults to "{}"'
    required: false
    default: "{}"
  ecs-compose-x-path:
    description: 'The AWS compose path. Defaults to "aws-compose-x.yaml"'
    required: false
    default: ""
  ecr-keep-last-n-images:
    description: 'The number of images to keep in the ECR repository. Defaults to 10.'
    required: false
    default: "10"

outputs:
  cf-output-path:
    description: 'A JSON string containing all CloudFormation outputs in JSON format'
    value: ${{ steps.deploy.outputs.cf-output-path }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('${GITHUB_ACTION_PATH}/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${GITHUB_ACTION_PATH}/requirements.txt -q

    - # Add support for more platforms with QEMU
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Cache Docker layers
    #   uses: actions/cache@v4
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-

    - name: Deploy
      shell: bash
      id: deploy
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        cd ${GITHUB_ACTION_PATH}
        python -m src.cli \
          --cf-stack-prefix=${{ inputs.cf-stack-prefix }} \
          --env-name=${{ inputs.env-name }} \
          --docker-compose-path=${{ inputs.docker-compose-path }} \
          --ecs-compose-x-sub='${{ inputs.ecs-compose-x-sub }}' \
          --ecs-compose-x-path=${{ inputs.ecs-compose-x-path }} \
          --ecr-keep-last-n-images=${{ inputs.ecr-keep-last-n-images }}
