version: '3.8'

services:
  django:
    image: "node:14"
    ports:
      - "3000:3000"
    restart: unless-stopped
    # depends_on:
    #   - redis

#   redis:
#     image: redis:6
#     volumes:
#       - redis_data:/data

# volumes:
#   redis_data:
